// <auto-generated />
namespace WatchAuthApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class User_Movies : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_Movies));
        
        string IMigrationMetadata.Id
        {
            get { return "201907100841225_User_Movies"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
